import Head from 'next/head';

import Navbar from '@components/Shared/Navbar';
import Announcements from '@components/Announcements';

const AnnouncementsPage = () => {
    return (
        <>
          <Head>
            <title>Nbhd</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/simple_logo_red.svg" />
          </Head>
          <main>
            <Navbar />
            <Announcements />
          </main>
        </>
    )
}

export default AnnouncementsPage